# Generated by Django 3.2.7 on 2021-11-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_first_name', models.CharField(max_length=20)),
                ('teacher_last_name', models.CharField(max_length=20)),
                ('teacher_mobile_no', models.IntegerField()),
                ('teacher_address', models.CharField(max_length=20)),
                ('teacher_education', models.CharField(max_length=20)),
                ('teacher_allocated_class', models.CharField(max_length=20)),
            ],
        ),
    ]
